added action

diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -5,18 +5,29 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
+      - uses: actions/setup-python@v3.9
+      - uses: syphar/restore-virtualenv@v1
+        id: pdpy-virtualenv
       - name: Install dependencies
         run: |
           pip install sphinx sphinx_rtd_theme
-      - name: Sphinx build
+      - name: Commit documentation changes
         run: |
-          sphinx-build doc _build
-      - name: Deploy
-        uses: peaceiris/actions-gh-pages@v3
-        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
-        with:
-          publish_branch: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: _build/
-          force_orphan: true
+          git clone https://github.com/pdpy-org/pdpy.git --branch gh-pages --single-branch gh-pages
+          make local
+          make docs
+          cp -r docs/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "fdch@nyu.edu"
+          git config --local user.name "Fede Camara Halac"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
